import sys
from collections import Counter

def analyze_log(file_path, is_friday=False):
    print(f"[*] Analyzing Log File: {file_path}")
    
    false_positives = []
    true_positives = []
    
    try:
        # 1. Read as raw bytes to bypass Windows encoding errors
        with open(file_path, 'rb') as f:
            raw = f.read()
        
        # 2. Smart Decode
        if raw.startswith(b'\xff\xfe') or raw.startswith(b'\xfe\xff'):
            text = raw.decode('utf-16', errors='ignore')
        else:
            text = raw.decode('utf-8', errors='ignore')
            
        # 3. Strip null bytes
        text = text.replace('\x00', '')
        lines = text.splitlines()
        
        # 4. Filter only attack lines
        attack_lines = [l for l in lines if "ATTACK" in l]
        print(f"[*] Total 'ATTACK' lines generated by AI: {len(attack_lines)}\n")
        
        for line in attack_lines:
            parts = line.strip().split('|')
            if len(parts) >= 4:
                try:
                    time_str = parts[0].strip().split(']')[0].replace('[', '')
                    conf_str = parts[1].strip().split(': ')[1]
                    ip_route = parts[2].strip()
                    port_str = parts[3].strip().split(': ')[1]
                    
                    if is_friday:
                        hour = int(time_str.split(':')[0])
                        minute = int(time_str.split(':')[1])
                        
                        # Define Clean Windows
                        is_fp = False
                        if hour < 13 or (hour == 13 and minute < 55): is_fp = True
                        elif hour == 14 and (15 <= minute < 51): is_fp = True
                        elif hour == 15 and (30 <= minute < 56): is_fp = True
                        elif hour == 16 and minute > 16: is_fp = True
                        elif hour >= 17: is_fp = True
                        
                        packet_data = {'time': time_str, 'port': port_str, 'route': ip_route, 'conf': conf_str}
                        
                        if is_fp:
                            false_positives.append(packet_data)
                        else:
                            true_positives.append(packet_data)
                    else:
                        # For a non-Friday custom PCAP, everything is an FP
                        false_positives.append({'time': time_str, 'port': port_str, 'route': ip_route})
                        
                except Exception:
                    continue # Skip malformed lines

        # --- TRUE POSITIVE STATS ---
        print("="*50)
        print(f"[+] TRUE POSITIVES (Attacks caught in attack windows): {len(true_positives)}")
        if len(true_positives) > 0:
            tp_ports = Counter([a['port'] for a in true_positives])
            print("    Top Target Ports for Real Attacks:")
            for p, count in tp_ports.most_common(3):
                print(f"      - Port {p}: {count} hits")

        # --- FALSE POSITIVE STATS ---
        print("\n" + "="*50)
        print(f"[-] FALSE POSITIVES (Alarms triggered in clean windows): {len(false_positives)}")
        if len(false_positives) > 0:
            fp_ports = Counter([a['port'] for a in false_positives])
            fp_ips = Counter([a['route'] for a in false_positives])
            
            print("    Top 5 Problematic Ports (Noise):")
            for p, count in fp_ports.most_common(5):
                print(f"      - Port {p}: {count} false alarms")
                
            print("\n    Top 5 Problematic IP Routes (Noise):")
            for route, count in fp_ips.most_common(5):
                print(f"      - {route}: {count} false alarms")
        print("="*50)
                
    except Exception as e:
        print(f"[-] Error: {e}")

if __name__ == "__main__":
    # Point this strictly to your log file
    analyze_log("logs/Friday_V3_1_improvedGuardrails.txt", is_friday=True)